### ISSUE TITLE
Crash on startup with "old" OpenGL driver on Linux

### ISSUE THREAD

**Issue by grorp** [minetest/irrlicht#277]
```
Fedora Linux 39 (Workstation Edition)
Intel® Core™ i7-4790K × 8
NVIDIA GeForce GTX 1080 Ti
```

Minetest minetest/minetest@8093044f071fc6ad20dbc0a07ba2ef824605fff5
Irrlicht 16c462c857cbce1ce35cb7d85749651334636fdd

crashes on startup

happens with the old OpenGL driver (`video_driver = opengl`), both with and without SDL2  
the new OpenGL driver is unaffected (`video_driver = opengl3`)

backtrace:

```
#0  0x0000000000000000 in ?? ()
#1  0x0000000000b7684f in irr::video::COpenGLCoreCacheHandler<irr::video::COpenGLDriver, irr::video::COpenGLCoreTexture<irr::video::COpenGLDriver> >::COpenGLCoreCacheHandler (
    this=this@entry=0x16e48a0, driver=<optimized out>) at /minetest/lib/irrlichtmt/source/Irrlicht/COpenGLCoreCacheHandler.h:227
#2  0x0000000000b76439 in irr::video::COpenGLCacheHandler::COpenGLCacheHandler (this=0x16e48a0, driver=<optimized out>)
    at /minetest/lib/irrlichtmt/source/Irrlicht/COpenGLCacheHandler.cpp:21
#3  0x0000000000b178f0 in irr::video::COpenGLDriver::genericDriverInit (this=this@entry=0x16d7100)
    at /minetest/lib/irrlichtmt/source/Irrlicht/COpenGLDriver.cpp:116
#4  0x0000000000b18320 in irr::video::COpenGLDriver::initDriver (this=this@entry=0x16d7100)
    at /minetest/lib/irrlichtmt/source/Irrlicht/COpenGLDriver.cpp:49
#5  0x0000000000b1837a in irr::video::createOpenGLDriver (params=..., io=0xe605f0, contextManager=contextManager@entry=0x16d5970)
    at /minetest/lib/irrlichtmt/source/Irrlicht/COpenGLDriver.cpp:4156
#6  0x0000000000acf8a0 in irr::CIrrDeviceSDL::createDriver (this=0xd8faf0) at /minetest/lib/irrlichtmt/source/Irrlicht/CIrrDeviceSDL.cpp:519
#7  irr::CIrrDeviceSDL::createDriver (this=0xd8faf0) at /minetest/lib/irrlichtmt/source/Irrlicht/CIrrDeviceSDL.cpp:509
#8  0x0000000000ad4cff in irr::CIrrDeviceSDL::CIrrDeviceSDL (this=this@entry=0xd8faf0, param=..., __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at /minetest/lib/irrlichtmt/source/Irrlicht/CIrrDeviceSDL.cpp:296
#9  0x0000000000ace00c in irr::createDeviceEx (params=...) at /minetest/lib/irrlichtmt/source/Irrlicht/Irrlicht.cpp:85
#10 0x00000000005b7c6c in createDevice (requested_driver=Python Exception <class 'gdb.error'>: value has been optimized out
..., params=...) at /minetest/src/client/renderingengine.cpp:102
#11 RenderingEngine::RenderingEngine (this=this@entry=0xe60410, receiver=<optimized out>) at /minetest/src/client/renderingengine.cpp:151
#12 0x00000000004d853d in ClientLauncher::init_engine (this=this@entry=0x7fffffffd5a0) at /minetest/src/client/clientlauncher.cpp:341
#13 0x00000000004deda6 in ClientLauncher::run (this=this@entry=0x7fffffffd5a0, start_data=..., cmd_args=...)
    at /minetest/src/client/clientlauncher.cpp:106
#14 0x00000000004b00d3 in main (argc=<optimized out>, argv=<optimized out>) at /minetest/src/client/clientlauncher.h:31
```

**Comment by grorp** [comment]
yeah I still had 16c462c857cbce1ce35cb7d85749651334636fdd which you've already force-pushed away from the master branch again

so it's all fine

**Comment by sfan5** [comment]
Yeah I realized it was not a safe incremental change and force-pushed it.
